### ISSUE TITLE
data.BidsToRemove

### ISSUE THREAD

**Issue by mGungorr** [burakoner/Paribu.Net#1]
Tekrardan Merhaba, 

Thodex ve Btcturk algoritmasında değişiklik yapmaya karar verdim,  yeni algoritması beni biraz zorladığı için şimdilik ara verdim ve o zamana kadar Paribuyu inceleyeyim dedim. Ancak sorun şu, Ben her coinin güncel fiyat listesini hafızada tutmaya çalışıyorum. Ama restten gelen fiyat bilgisi (100000) Tl gibi, websockette data.bidsToAdd'den gelen (100000.0000) Tl gibi,  == şeklinde kullandığımda problem olmuyor noktadan sonrası aynı olduğu için ama bidsToRemove ile gelen price verisi (1000000000) tl şeklinde geliyor. Yani farklı veriymiş gibi geldiği için listeden silemiyorum. Her coinin fiyat hanesi farklı olduğu için ve hane sayısı da değişebileceği için kesin bi çözüm bulamadım. 

Sizin aklınıza gelen bir yol olabilir mi acaba ?

![image](https://user-images.githubusercontent.com/69353577/104815070-67974a80-5823-11eb-841e-454f48512995.png)

Görseldeki fiyat aslında (271817.79) TL

**Comment by burakoner** [comment]
Bana bu çok ilginç gelmişti çünkü bende gayet normal gösteriyordu. Resim-1 de görebilirsin. anladığım kadarıyla Visual Studio'yu İngilizce kullanıyorsun ama işletim sistemin Türkçe (Benim windows da ingilizce). Çünlü yaptığım testlerde Türkçe CultureInfo ile okumaya zorladığımda senin aldığın sonucu aldım. Resimlerini inceleyebilirsin. Bu durumda mevcut sürümü kullanarak thread varsayılan CultureInfo'sunu Invariant yaparsan sorun çözülür senin için. İşi düzgün yolla halletmek için kullanıcının ek kod yazmasına gerek bırakmayacak bir düzenleme yaptım. Birazdan hem buraya hem de nuget'e yüklemiş olurum.

![Screenshot_1](https://user-images.githubusercontent.com/21169085/104819601-86a3d580-583f-11eb-86c2-3a325e40fe5f.png)
![Screenshot_2](https://user-images.githubusercontent.com/21169085/104819602-873c6c00-583f-11eb-8792-9c62867c93dc.png)
![Screenshot_3](https://user-images.githubusercontent.com/21169085/104819603-87d50280-583f-11eb-867f-f0f2310cb5ec.png)

**Comment by mGungorr** [comment]
Evet tahmin ettiğiniz gibi Visual Studio ingilizce, windows single language türkçe :) Teşekkür ediyorum, şuan beklediğim gibi çalışıyor.

**Comment by burakoner** [comment]
Çok sevindim. Konuyu kapatıyorum o halde.
