### ISSUE TITLE
Transfer problem

### ISSUE THREAD

**Issue by ghostguv** [burakoner/Paribu.Net#10]
Hi thanks for your effort. I am using your nuget package. I like it. But I there is something missing for withdraw. It need google authenticator and e mail confirmation to make transfer. Is there any plan for that ? Thanks for great work.

**Comment by burakoner** [comment]
As you know there is no documentation for that API usage. I'm not sure but I think there isnt any extra OTP endpoint. Register, Login, Wthdrawal should use same OTP method. just try LoginOtp or RegisterOtp method for withdrawal for now. If I found correct answer I'll share with you.

**Comment by ghostguv** [comment]
Thanks for your response. I am waiting for correct solution. Other than that Is it possible to get all orderbook data other than addedbids , removedbids etc for subscribe orderbook response

**Comment by burakoner** [comment]
Unfortunatelly
