### ISSUE TITLE
Two-factor

### ISSUE THREAD

**Issue by NeutK** [burakoner/Paribu.Net#11]
Merhaba hocam, öncelikle elinize sağlık. Ben kodumu python da geliştiriyorum. Ornek metotlarınızdan "LoginTwoFactor" metotunu çağırdıktan sonra bir tane token dönüyor. Bu da accesstoken (p08.data.Token) olarak kaydediliyor. Fakat aynı request i ben python'da yaptığımda böyle bir token dönmüyor. Aynı işlemi manuel olarak yaptım. Donen mesajda da görünmüyor. Bu token ı nasıl elde edebilirim ?

**Comment by UtkuX** [comment]
> 

@NeutK Merhaba, elde edebilmenin yolunu bulabildin mi?

**Comment by NeutK** [comment]
Hocam merhaba, tekrar bakabilme şansım yeni oldu. Örnek kodunuzda ParibuTwoFactorUser objesi icerisinde tutulan "Token" değişkeni(önceki yorumda bahsettiğim accessToken) daha sonra private requestlerde headers içerisinde bearer token olarak kullanılıyor. Sizin kodunuzda sendRequestAsync fonksiyonu bearer token ile beraber dönüyor. 
 `var result = await SendRequestAsync<ParibuApiResponse<ParibuTwoFactorUser>>(GetUrl(Endpoints_Public_TwoFactor), method: HttpMethod.Post, ct, parameters, checkResult: false, signed: false).ConfigureAwait(false);`

CryptoExchange.Net ' in SendRequestAsync fonksiyonunu biraz inceledim fakat, nasıl bearer token'i elde ettiğini anlayamadım. Python'da benzer bir request yaptığımda bearer token dönmüyor. Aynı şekilde browserda Fetch/XHR request leri incelediğimde de bearer token görünmüyor. 
Bearer token JWT encoding ile headers response da saklanabiliyormuş. Bir kaç tane headers response da  JWT encoding key'i buldum fakat bearer token a ulaşamadım.
