### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by ksencez** [burakoner/Paribu.Net#12]
Hocam merhaba öncelikle emeğiniz için teşekkür ederim. Paribu sistemi şuan her cihaz için mail ile onaylı giriş sistemi getirdi. Kütüphanenizin mevcut halinde onay versek bile token bilgisini çektiremiyorum.  Paribu onaydan sonra tekrar login olmayı istiyor tekrar yazdığınız kütüphane ile tekrar login süreçlerini başlatıyorum ancak yine mail geliyor token bilgisi gelmiyor. Yardımcı olabilir misiniz?

**Comment by ninja342** [comment]
Aynı durumu ben de yaşıyorum. Bir çözüm bulabildiniz mi?
