### ISSUE TITLE
LoginTwoFactor

### ISSUE THREAD

**Issue by agorkemsekerci** [burakoner/Paribu.Net#14]
Merhaba,

Login sürecinden token bilgisi geliyor. OTP ile üretilen kod ile LoginTwoFactor çağırdığımda Token bilgisi boş geliyor.
Uygulama içerisindeki Paribu.Net.Login console uygulamasını çalıştırdığımda da aynı problem oluyor. Yeni bir cihazda oturum açıyorsunuz maili geliyor. Bu kısmı nasıl aşabiliriz?

**Comment by burakoner** [comment]
Başkaları da bu sorundan bahsetti ama ben normal login olabiliyorum. Bana bir mail örneği iletebilir misin? info@burakoner.com

**Comment by agorkemsekerci** [comment]
Mail gönderdim.

**Comment by burakoner** [comment]
Teşekkürler. Tahmin edeceğin üzere aslında maildeki linki merak etmiştim. Şimdilik buradan birşey çıkarmak güç. Issue benim aklımda çözmeye çalışacağım.

**Comment by agorkemsekerci** [comment]
Selam, Header eklediğin aşağıdakiler nasıl tespit ediyorsun? Windows Chrome veya IOS için nasıl ekleniyor?
Hiç android cihazdan giriş yapmadığım için olabilir mi?

headers.Add("user-agent", "ParibuApp/345 (Android 12)");
headers.Add("x-app-version", "345");

**Comment by burakoner** [comment]
Bu soruyu cevaplamamayı tercih ediyorum ama sanırım sen de çözmüşsün zaten. Yardımların için teşekkür ederim. Sayende sorunu çözdük. https://github.com/burakoner/Paribu.Net/commit/228b12856bc64c963b4ea66d724c42b3a94e4019 ile sorun halloldu. Test için mutlaka Paribu.Net.Login projesini denemelisin. Nuget paketini de güncelledim. Tekrar teşekkürler.
