### ISSUE TITLE
"Bir PARIBU.NET (Android) cihazda, Paribu Android uygulaması kullanılarak oturum açılıyor." problemi

### ISSUE THREAD

**Issue by odurmus06** [burakoner/Paribu.Net#15]
Merhaba. login olduktan sonra gönderilen yeni cihaz doğrulama kodu tarafıma mail atılıyor ama  login işlemini android cihazdan yapıldığını zannettiği için bilgisayarımı yeni cihaz olarak tanımlatamıyorum. bir çözümü var mıdır? teşekkürler

**Comment by burakoner** [comment]
https://github.com/burakoner/Paribu.Net/blob/master/Paribu.Net.Login/Program.cs bunu inceledin mi

**Comment by odurmus06** [comment]
> https://github.com/burakoner/Paribu.Net/blob/master/Paribu.Net.Login/Program.cs bunu inceledin mi

hocam bu kodu çalıştırdığında aynı hatayı alıyor musunuz?

**Comment by burakoner** [comment]
Cihaz kimliği için öncelikle rastgele bir değer girip login olmalısın. Devamında yapacağın requestler için aynı değeri girmelisin

**Comment by odurmus06** [comment]
> Cihaz kimliği için öncelikle rastgele bir değer girip login olmalısın. Devamında yapacağın requestler için aynı değeri girmelisin

yaptığım işlemler birebir aynı. oturum onaylama mailini android emulatörde açıp onaylayınca sorun çözüldü.
