### ISSUE TITLE
Al - Sat emri gönderme

### ISSUE THREAD

**Issue by mGungorr** [burakoner/Paribu.Net#2]
Merhaba, 

Alım satım stratejisi üzerinde çalışıyorum ama emir gönderemiyorum. Aklımda selenium seçeneği var ama sayfanın yüklenmesi vs emri gönderene kadar coinin fiyat - miktar değerlerinin değişmesi çok olası. Daha hızlı bir şekilde nasıl emir gönderebilirim. Araştırmalarım sonucu WebClient -  HttpClient -  HttpWebRequest vs. gibi şeyler buldum ama bunlar gerçekten aradığım şeyler mi yada hangisi bana uygun anlam veremedim.

Bi kaç yerde sordum nasıl yapabileceğime dair şu şekilde bir cevap aldım ama yine de bi şey oluşmadı bende.

> OK, so this is a Vue website, which means it's most likely talking to a JSON API. Potentially you can look at the code in the page, figure out how the API works and hit it directly

Neyi araştırmamı önerirsiniz , hangi yöntem ile en hızlı şekilde emir gönderebilirim ?

**Comment by burakoner** [comment]
Paribu'da şu an bir varlığım yok. O nedenle kod yerine sadece tekniği verebilirim.
Konsol penceresini açıp oradan XHR işlemlerini takip etmelisin. Siteden bir emir gönder ve bu emri XHR'den yakalayıp onu kendi istediğin parametrelere göre kodlarla taklit etmelisin. İşi koda dökmeden önce Postman gibi bir araç kullanarak hızlı yol alabilirsin. Selenium bu işe uygun olmaz. Emir göndermek için ihtiyaç duyacağın parametreleri Cookie ve Local Storage'ten alabilirsin.

![Screenshot_1](https://user-images.githubusercontent.com/21169085/104835028-c2c54d80-58b4-11eb-8471-7c1211d8fd71.png)

![Screenshot_2](https://user-images.githubusercontent.com/21169085/104835030-c3f67a80-58b4-11eb-8857-ad2359f5dcc7.png)

**Comment by mGungorr** [comment]
Tamamdır ,çok yardımcı oldu görseller , teşekkür ederim. Final haftamdan sonra tekrar başlayacağım uğraşmaya, şimdilik kapatıyorum sorunu. Yeni bir şey olursa buraya comment olarak eklerim.

**Comment by mGungorr** [comment]
Ben söylediğiniz gibi yaptım, bir haftadır her denemem de sorunsuz çalışıyordu. Bugun emir denemelerimde al-sat yapamadım, kontrol ettim ve requestlerim nulldu. Bi kaç saat uğraştıktan sonra tekrar postman ile deneme yapayım dedim, **Status: 403 Forbidden**  diyor. Post ettikten sonra preview ettiğimde ise cloudflare ekranı geliyor. **One more step
Please complete the security check to access www.paribu.com........... gibi gibi** Cloudflareden dolayı tüm emir gönderme sistemim bozuldu , nasıl aşabilirim bunu, bi fikriniz var mı ?

**Comment by burakoner** [comment]
Cloudflare proxy görevi görüyor ve muhtemelen arada kullandığı parametreleri güvenlik gerekçesiyle değiştiriyor. Paribunun normal sitesine girerek cookie leri yeniden almanı öneririm.

**Comment by mGungorr** [comment]
Hesaptan çıkış yapti vs diye düşünüp yeni cookie ile denemistim, Yeni cookiede de eskisinde de cloudflare geliyo maalesef. Hem localde hem sunucudan denedim ip'ye özel bir sey de değil ama şöyle bi sey var. Ben siteyi ilk kez actigimda bana da cloudflare geliyo, o kısmı gectikten sonra bi daha gelmiyo ve her zaman cloudflare kullanmıyorlar, coinler hareketliyken site yogunlugu artiyor muhtemelen o zaman açıyorlar. Browserdan el ile siteye giris yapip cloudflare kismini gectikten sonra botu calistirdigimda da proxy ekraninin gelmemesi gerekmez miydi, Ayni cihaz ilr baglaniyorum sonuçta ? 

Simdi tekrar denedim cloudflare kullanmadiklari için calisiyor, Biraz Allah'a emanet bi sistem olacak galiba

**Comment by burakoner** [comment]
Kaçak API böyle oluyor maalesef

**Comment by mGungorr** [comment]
Anladım, bu kadarı bile çok iyi, olduğu kadar artık. Teşekkürler

**Comment by samemen** [comment]
> Hesaptan çıkış yapti vs diye düşünüp yeni cookie ile denemistim, Yeni cookiede de eskisinde de cloudflare geliyo maalesef. Hem localde hem sunucudan denedim ip'ye özel bir sey de değil ama şöyle bi sey var. Ben siteyi ilk kez actigimda bana da cloudflare geliyo, o kısmı gectikten sonra bi daha gelmiyo ve her zaman cloudflare kullanmıyorlar, coinler hareketliyken site yogunlugu artiyor muhtemelen o zaman açıyorlar. Browserdan el ile siteye giris yapip cloudflare kismini gectikten sonra botu calistirdigimda da proxy ekraninin gelmemesi gerekmez miydi, Ayni cihaz ilr baglaniyorum sonuçta ?
> 
> Simdi tekrar denedim cloudflare kullanmadiklari için calisiyor, Biraz Allah'a emanet bi sistem olacak galiba

Php olarak linux üzerinden normal api gibi kullanıyorum paribu sagolsun ip adresini cloudflare'ye whiteliste ekledi mail atarak bu durumu cözebilirsiniz. Ayrıca api önümüzdeki ay gelicek aldıgım bilgiye göre.
