### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException

### ISSUE THREAD

**Issue by mGungorr** [burakoner/Paribu.Net#3]
![image](https://user-images.githubusercontent.com/69353577/106405052-ea382080-6445-11eb-834e-8f5aba924767.png)

Merhaba Burak abi, şöyle bir hata aldım. Önemli olabilir diye data.Datanın içini de koyayım şuraya.

`{"index":"orderBook","patch":{"unset":["sell\/2.19000000"],"merge":[],"label":""}}`

Markette bi sorun da yok, neden bu şekilde bi hata almış olabilir ?

**Comment by burakoner** [comment]
Örnek veriyi göndermen çok iyi oldu. Çünkü ne kadar beklediysem bu hatayı yakalayamadım. Gönderdiğin veri üzerinden konuşursak `"merge":[]` kısmında problem var. Burada normalda array olmayan bir obje döndürmesi lazım ama içerik boşsa `null` göndermek yerine belli ki Paribu `[]` şeklinde göndermeyi uygun bulmuş.

https://github.com/burakoner/Paribu.Net/commits/master committe düzelttim ve nuget paketini de gönderdim. kolaylıklar diliyorum

**Comment by mGungorr** [comment]
Bazı gariplikleri var paribunun maalesef, teşekkür ederim.
