### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by mGungorr** [burakoner/Paribu.Net#4]
Merhaba Burak Abi, projeyi biraz daha büyütmeye ve farklı borsalar da eklemeye karar verdim. Jkorf'un bazı clientlerini de ekleyince şu hatayı aldım.
![image](https://user-images.githubusercontent.com/69353577/108036250-085a6f00-7049-11eb-8d45-ce78011ccb43.png)

Sorun bende mi yoksa CryptoExchange versiyonu (_edited._ 3.6.0 imiş yani son versiyon, hata başka bi şeyden dolayı sanırım) falan mı farklı çözemedim. Bu projeyi diğer borsa clientlerine ekleyince de , bu sefer onlar farklı hata veriyo.

**Comment by burakoner** [comment]
Version uyumsuzluğu olabilir. Tüm referansların aynı version olduğundan emin ol

**Comment by mGungorr** [comment]
Diğer clientlerin CryptoExchange versiyonları güncel değilmiş, sorun halloldu. Teşekkürler
