### ISSUE TITLE
Emir sonucunda minimum emir miktarı hatası

### ISSUE THREAD

**Issue by mtardal** [burakoner/Paribu.Net#9]
Merhaba,

Öncelikle bu kullanışlı wrapper için çok teşekkürler.

Piyasada emir vermeye çalıştığımda "XXX marketinde minimum emir miktarı YYY olmalıdır." gibi bir hata alıyorum fakat emir verirken kullandığım miktar, aşağıdaki ekran görüntüsünde de görüldüğü gibi bu belirtilen minimum miktarın zaten üstünde. Sizce bunun sebebi ne olabilir, aklınıza gelen bir şey var mı?

![Screenshotg_1](https://user-images.githubusercontent.com/22726842/143262976-7dfdecbc-815a-4133-85ae-98eb1082dbde.png)

**Comment by burakoner** [comment]
Öncelikle bunun resmi bir API olmadığını, dokümantasyonun bulunmadığını hatırlatmak isterim. Bu nedenle sadece tahmin yürütebiliyorum. 
- Kasdedilen miktar SHIB veya TL olabilir ama miktara bakınca mutlaka SHIB'dir diye düşünüyorum.
- Direkt 100.000 ile deneme yaptın mı? 
- Aklıma gelen en mantıklı açıklama şu ki; Borsaların bizimle paylaşmadıkları ama aplikasyonlarının bildikleri bazı parametreler vardır. Bunlardan bir tanesi de Step kavramı. Bu hem Fiyata hem de Miktara uygulanabilir. Yani alt limit 100.000 SHIB'dir ama bundan bir fazla satmak için 10.000'nin katları olması gerekir gibi.
Sadece mantık yürüttüm hatanın sebebini bilmiyorum. Aklıma başka bir nokta gelirse de mutlaka yazarım yeniden.

**Comment by mtardal** [comment]
Yanıt için teşekkürler. Manuel bir şekilde paribu üzerinden emir verip gönderilen HTTP request'i inceledim. Piyasa emri için "amount" field'ı kullanılıyor fakat PlaceOrder fonksiyonunda "total" argümanı zorunlu. PlaceOrder fonksiyonunda "total" yerine "amount" zorunlu argüman olursa sorun çözülebilir sanırım.
![resim](https://user-images.githubusercontent.com/22726842/143461965-80a26ef1-3318-4985-9d1b-d8c3924eef0f.png)

**Comment by burakoner** [comment]
Ok geri bildirimin için teşekkür ederim.

**Comment by burakoner** [comment]
başka birkaç küçük hata vardı. Onlarla birlikte yeni version çıktım. Bildirimin için yeniden teşekkür ederim.
